
name: GitHub Actions Build and Deploy 
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: npm install, build
      run: npm install && npm run build
      env:
        ACCESS_TOKEN: ${{ secrets.token }}
    - name: log
      run: echo ls $(ls -la)
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-west-1'   # optional: defaults to us-east-1
        SOURCE_DIR: 'my-wesite/README.md'      # optional: defaults to entire repository
    #     args: --acl public-read --follow-symlinks --delete